package org.jboss.xavier.integrations.migrationanalytics.input;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.kie.api.definition.type.Label;

/**
 * This class was automatically generated by the data modeler tool.
 */

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class InputDataModel implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private Long id;

    @Label(value = "Customer ID")
    private String customerId;

    @Label(value = "Source payload file name")
    private String fileName;

    @Label(value = "Number of hosts found")
    private Integer numberOfHosts;

    @Label(value = "Total disk space used found ")
    private Long totalDiskSpace;

}
