{
 "title": "Migration Analytics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "up{kubernetes_namespace=~\"platform-[a-z]*\"}"
   },
   {
    "name": "kibana",
    "query": "https://kibana-kibana.5a9f.insights-dev.openshiftapps.com/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-12h,mode:quick,to:now))&_a=(columns:!(_source),index:d2da0310-7048-11e9-a501-7998195d35a8,interval:auto"
   },
   {
    "name": "kibana_dev",
    "query": "https://kibana-kibana.5a9f.insights-dev.openshiftapps.com/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-12h,mode:quick,to:now))&_a=(columns:!(_source),index:d2da0310-7048-11e9-a501-7998195d35a8,interval:auto"
   },
   {
    "name": "kibana_prod",
    "query": "https://kibana-kibana.1b13.insights.openshiftapps.com/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-12h,mode:quick,to:now))&_a=(columns:!(_source),index:'0a2575c0-65f9-11e9-ba88-097c6c9f6850',interval:auto"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "content": "<center><h1>Overview</h1></center>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "content": "<center><h1>3scale</h1></center>"
  },
  {
   "title": "xavier-integration pod count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(up{kubernetes_namespace='xavier-$namespace', deploymentconfig=\"analytics-integration\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "postgresql pod count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace='xavier-$namespace', phase=\"Running\", pod=~\"postgresql-.*\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Aprox. VMs analyzed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(org_apache_camel_ExchangesTotal{route='\"extract-vmworkloadinventory\"', kubernetes_namespace='xavier-$namespace'}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "2xx ratio",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_status{service=\"xavier\", status=\"2xx\", environment=\"$namespace\"}[$__range])) / sum(increase(api_3scale_gateway_api_status{service=\"xavier\", environment=\"$namespace\"}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "2xx total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_status{service=\"xavier\", status=\"2xx\", environment=\"$namespace\"}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "3scale API Requests",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_status{service=\"xavier\", environment='$namespace'}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "broker pod count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace='xavier-$namespace', phase=\"Running\", pod=~\"broker-amq-.*\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Uploads",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(org_apache_camel_ExchangesTotal{route='\"direct-upload\"', kubernetes_namespace='xavier-$namespace'}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uploads Failed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(org_apache_camel_FailuresHandled{route='\"calculate\"', kubernetes_namespace='xavier-$namespace'}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "3xx ratio",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_status{service=\"xavier\", status=\"3xx\", environment=\"$namespace\"}[$__range])) / sum(increase(api_3scale_gateway_api_status{service=\"xavier\", environment=\"$namespace\"}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "3xx total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_status{service=\"xavier\", status=\"3xx\", environment=\"$namespace\"}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "rhdmcentr pod count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace='xavier-$namespace', phase=\"Running\", pod=~\"analytics-rhdmcentr-.*\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "kieserver pod count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 6 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace='xavier-$namespace', phase=\"Running\", pod=~\"analytics-kieserver-.*\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "4xx ratio",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 6 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_status{service=\"xavier\", status=\"4xx\", environment=\"$namespace\"}[$__range])) / sum(increase(api_3scale_gateway_api_status{service=\"xavier\", environment=\"$namespace\"}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "4xx total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_status{service=\"xavier\", status=\"4xx\", environment=\"$namespace\"}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 8 },
   "content": "<center><h1>Camel Routes</h1></center>"
  },
  {
   "title": "5xx ratio",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 8 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_status{service=\"xavier\", status=\"5xx\", environment=\"$namespace\"}[$__range])) / sum(increase(api_3scale_gateway_api_status{service=\"xavier\", environment=\"$namespace\"}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "5xx total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_status{service=\"xavier\", status=\"5xx\", environment=\"$namespace\"}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 0, "y": 10 }, "content": "<center><h1>RBAC</h1></center>" },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 10 },
   "content": "<center><h1>Kie Server</h1></center>"
  },
  {
   "title": "Latency",
   "type": "heatmap",
   "description": "The time it takes to service a request",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_time_bucket{service=\"xavier\", environment=\"$namespace\"}[1m])) by (le)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}} ms",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mean Execution Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 12 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "org_apache_camel_MeanProcessingTime{kubernetes_namespace='xavier-$namespace', processor='\"fetch-rbac-user-access-endpoint\"'}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RBAC Errors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(org_apache_camel_ExchangesFailed{kubernetes_namespace='xavier-$namespace', processor='\"fetch-rbac-user-access-endpoint\"'}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mean Execution Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 12 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "org_apache_camel_MeanProcessingTime{kubernetes_namespace='xavier-$namespace', processor='\"route-to-decision-server-rest\"'}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "KIE handled errors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(org_apache_camel_FailuresHandled{kubernetes_namespace='xavier-$namespace', processor='\"route-extract-ics-reports\"'}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "KIE errors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(org_apache_camel_ExchangesFailed{kubernetes_namespace='xavier-$namespace', processor='\"route-to-decision-server-rest\"'}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "org_apache_camel_MeanProcessingTime{kubernetes_namespace='xavier-$namespace', processor='\"fetch-rbac-user-access-endpoint\"'}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "org_apache_camel_MeanProcessingTime{kubernetes_namespace='xavier-$namespace', processor='\"route-to-decision-server-rest\"'}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "description": "How much demand is being placed on the system",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_3scale_gateway_api_time_count{service=\"xavier\", environment=\"$namespace\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 20 },
   "content": "<center><h1>AWS S3</h1></center>"
  },
  {
   "title": "Mean Execution Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 22 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "org_apache_camel_MeanProcessingTime{kubernetes_namespace='xavier-$namespace', processor='\"s3-call\"'}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "s3-call errors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(org_apache_camel_ExchangesFailed{kubernetes_namespace='xavier-$namespace', processor='\"s3-call\"'}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mean Execution Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 22 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "org_apache_camel_MeanProcessingTime{kubernetes_namespace='xavier-$namespace', processor='\"fetch-rbac-user-access-endpoint\"'}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "aws-s3-get-download-link errors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(org_apache_camel_ExchangesFailed{kubernetes_namespace='xavier-$namespace', processor='\"aws-s3-get-download-link\"'}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 24 },
   "content": "<center><h1>Camel Routes</h1></center>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 26 },
   "content": "<center><h1>Important routes</h1></center>"
  },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 6, "y": 26 }, "content": "<center><h1>Flow</h1></center>" },
  {
   "title": "Mean Execution Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 28 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "org_apache_camel_MeanProcessingTime{route='\"reports-get-all\"', kubernetes_namespace='xavier-$namespace'}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "upload",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 28 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(org_apache_camel_ExchangesTotal{route='\"direct-upload\"', kubernetes_namespace='xavier-$namespace'}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(org_apache_camel_ExchangesTotal{route='\"reports-get-all\"', kubernetes_namespace='xavier-$namespace'}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "insights upload",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 30 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(org_apache_camel_ExchangesTotal{route='\"call-insights-upload-service\"', kubernetes_namespace='xavier-$namespace'}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "reevaluate-workload-inventory-reports total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 32 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(org_apache_camel_ExchangesTotal{route='\"reevaluate-workload-inventory-reports\"', kubernetes_namespace='xavier-$namespace'}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "S3",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 32 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(org_apache_camel_ExchangesTotal{processor='\"s3-call\"', kubernetes_namespace='xavier-$namespace'}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "kafka message",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 32 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(org_apache_camel_ExchangesTotal{route='\"kafka-upload-message\"', kubernetes_namespace='xavier-$namespace'}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "calculate",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 34 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(org_apache_camel_ExchangesCompleted{route='\"calculate\"', kubernetes_namespace='xavier-$namespace'}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "analyze VM",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 36 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(org_apache_camel_ExchangesTotal{route='\"extract-vmworkloadinventory\"', kubernetes_namespace='xavier-$namespace'}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 39 },
   "content": "<center><h1>Openshift</h1></center>"
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace='xavier-$namespace', container_name=\"analytics-integration\"}",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "container_memory_usage_bytes{namespace='xavier-$namespace', container_name=\"postgresql\"}",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "container_memory_usage_bytes{namespace='xavier-$namespace', container_name=\"analytics-rhdmcentr\"}",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "container_memory_usage_bytes{namespace='xavier-$namespace', container_name=\"analytics-kieserver\"}",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "container_memory_usage_bytes{namespace='xavier-$namespace', container_name=\"broker-amq\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace='xavier-$namespace', container_name=\"analytics-integration\"}[5m])",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace='xavier-$namespace', container_name=\"postgresql\"}[5m])",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace='xavier-$namespace', container_name=\"analytics-rhdmcentr\"}[5m])",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace='xavier-$namespace', container_name=\"analytics-kieserver\"}[5m])",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace='xavier-$namespace', container_name=\"broker-amq\"}[5m])",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Percentage of CPU limit consumed",
   "type": "graph",
   "description": "CPU consumption plotted against configured CPU limit of service",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace='xavier-$namespace',container_name=\"analytics-integration\"}[1m])) / sum(kube_pod_container_resource_limits_cpu_cores{namespace='xavier-$namespace',container=\"analytics-integration\"})",
     "legendFormat": "analytics-integration"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace='xavier-$namespace',container_name=\"postgresql\"}[1m])) / sum(kube_pod_container_resource_limits_cpu_cores{namespace='xavier-$namespace',container=\"postgresql\"})",
     "legendFormat": "postgresql"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace='xavier-$namespace',container_name=\"analytics-rhdmcentr\"}[1m])) / sum(kube_pod_container_resource_limits_cpu_cores{namespace='xavier-$namespace',container=\"analytics-rhdmcentr\"})",
     "legendFormat": "analytics-rhdmcentr"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace='xavier-$namespace',container_name=\"analytics-kieserver\"}[1m])) / sum(kube_pod_container_resource_limits_cpu_cores{namespace='xavier-$namespace',container=\"analytics-kieserver\"})",
     "legendFormat": "analytics-kieserver"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace='xavier-$namespace',container_name=\"broker-amq\"}[1m])) / sum(kube_pod_container_resource_limits_cpu_cores{namespace='xavier-$namespace',container=\"broker-amq\"})",
     "legendFormat": "broker-amq"
    }
   ]
  }
 ]
}